config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  get 'admin/update'

  devise_for :users, :controller => { sessions: 'users/sessions',:omniauth_callbacks => "users/omnniauth_callbacks" }

  resources :apartments

  root 'apartments#index'

  get "admin" => "admin#index"

  put "admin/:id" => "admin#update"

  patch "admin/:id" => "admin#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

      user ||= User.new # dummy user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :default_renter
        can :create, Apartment, user_id: user.id #can only edit or delete what they created
        can :update, Apartment, user_id: user.id #can only edit or delete what they created
        can :delete, Apartment, user_id: user.id #can only edit or delete what they created
        can :read, Apartment #can view all apartments
      end
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :user

  resourcify #this is the resource that can be managed based on roles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :apartments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:twitter]

  after_create :assign_role

   def assign_role
     add_role(:default_renter) #whenever a new user is created, automatically assing them the 'default_renter'
   end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.uid + "@twitter.com"
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize #see method below

  def index
    @users = User.all #display all users on the admin page
  end

  def update
    user = User.find(params[:id])
    #user.remove_role user.roles.last-- user only has one role
    user.add_role(:admin)
    redirect_to '/admin'
  end

  private

  def authorize
    if !current_user.has_role? :admin
      render text:"No access for you!"
    end
  end #make sure anyone who is not an admin cannot do anything in this controller

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:index, :show] #no need to authorize resource if only viewing index page .

  # GET /apartments
  # GET /apartments.json
  def index
    @ability = Ability.new(current_user)
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    
  end

  # GET /apartments/new
  def new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
          format.html {
            redirect_to '/', notice: 'You do not have permission to access this page!' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:street_1, :street_2, :city, :postal_code, :state, :country, :name, :phone_number, :hours_to_contact, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @user.save

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["users.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th><%= user.email %></th>
      <td><%= user.roles.try(:pluck, :name).try(:join, (', ')) %></td> <!-- show all roles the user has-->
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=teacher", method: :PUT) do %>
          <input type="submit" value="Make Admin"/>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_for(apartment) do |f| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_1 %>
    <%= f.text_field :street_1 %>
  </div>

  <div class="field">
    <%= f.label :street_2 %>
    <%= f.text_field :street_2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :postal_code %>
    <%= f.number_field :postal_code %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :hours_to_contact %>
    <%= f.text_field :hours_to_contact %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Apartment', new_apartment_path %>
<% end %>

<h1>View all apartments</h1>

<% @apartments.each do |apartment| %>

  <p>
    <strong><%= apartment.name %></strong> <br>
    <a href="/apartments/<%= apartment.id%>">
      <%= apartment.street_1 %>, <%= apartment.city %> <br>
      <%= apartment.state %> <br>
    <em><% if can? :edit, apartment %></a> <%= link_to 'Edit', edit_apartment_path(apartment) %><% end %> <% if can? :delete, apartment %><%= link_to 'Destroy', apartment, method: :delete %><% end %></em><br>
  </p>

<% end %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p>
  <strong>Street 1:</strong>
  <%= @apartment.street_1 %>
</p>

<p>
  <strong>Street 2:</strong>
  <%= @apartment.street_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @apartment.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @apartment.phone_number %>
</p>

<p>
  <strong>Hours to contact:</strong>
  <%= @apartment.hours_to_contact %>
</p>

<% if can? :edit, @apartment, user_id: current_user.id %>
  <p>
    <%= link_to 'Edit', edit_apartment_path(@apartment) %>
  </p>
<% end%>
<% if can? :delete, @apartment, user_id: current_user.id %>
  <p>
    <%= link_to 'Destroy', apartment_path(@apartment) %>
  </p>
<% end %>
<p><%= link_to 'Back', apartments_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApartmentAppp</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <!-- navigation -->
      <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Apartment App", apartments_path, class: 'navbar-brand' %>
          </div>

          <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', root_path %></li>
              <% if !current_user %>
                <li><%= link_to 'Login', new_user_session_path %></li>
              <% elsif current_user %>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav> <!-- END NAVBAR -->

    <div class="row">

      <div class="col-md-6">
        <p><%= flash[:notice] %></p>
      </div>

      <div class="col-md-6">
        <p><%= flash[:alert] %></p>
      </div>

    </div>

        <%= if !current_user.nil?
          current_user.email + ' (' + current_user.roles.pluck(:name).join(", ") + ')'
            end
            #pluck grabs out from every element of the array the NAME property value of that instance.
        %>
      </p>
      <%= yield %>
    </div>
  </body>
</html>